#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "../header_files/file_configure.h"
#include "../header_files/folder_configure.h"
#include "../header_files/news_configure.h"
#include "../header_files/search_configure.h"

namespace py = pybind11;

PYBIND11_MODULE(angel_configure, m) {
    py::class_<File>(m, "File")
        .def(py::init<>())
        .def("create_file", &File::create_file)
        .def("write_file", &File::write_file)
        .def("read_file", &File::read_file)
        .def("delete_file", &File::delete_file)
        .def("rename_file", &File::rename_file)
        .def("move_file", &File::move_file)
        .def("copy_file", &File::copy_file)
        .def("check_file", &File::check_file)
        .def("hide_file", &File::hide_file)
        .def("unhide_file", &File::unhide_file);

    py::class_<Folder>(m, "Folder")
        .def(py::init<>())
        .def("create_folder", &Folder::create_folder)
        .def("list_folder", &Folder::list_folder)
        .def("delete_folder", &Folder::delete_folder)
        .def("rename_folder", &Folder::rename_folder)
        .def("move_folder", &Folder::move_folder)
        .def("copy_folder", &Folder::copy_folder)
        .def("check_folder", &Folder::check_folder)
        .def("hide_folder", &Folder::hide_folder)
        .def("unhide_folder", &Folder::unhide_folder);
    
    py::class_<GoogleNews>(m, "GoogleNews")
        .def(py::init<>())
        .def("get_language", &GoogleNews::get_language)
        .def("get_country", &GoogleNews::get_country)
        .def("get_period", &GoogleNews::get_period)
        .def("get_start_date", &GoogleNews::get_start_date)
        .def("get_end_date", &GoogleNews::get_end_date)
        .def("get_max_results", &GoogleNews::get_max_results)
        .def("get_exclude_websites", &GoogleNews::get_exclude_websites)
        .def("get_news", &GoogleNews::get_news)
        .def("get_latest_topics", &GoogleNews::get_latest_topics)
        .def("get_news_by_topic", &GoogleNews::get_news_by_topic)
        .def("get_news_by_country", &GoogleNews::get_news_by_country)
        .def("get_news_by_site", &GoogleNews::get_news_by_site)
        .def("set_language", &GoogleNews::set_language)
        .def("set_country", &GoogleNews::set_country)
        .def("set_period", &GoogleNews::set_period)
        .def("set_start_date", &GoogleNews::set_start_date)
        .def("set_end_date", &GoogleNews::set_end_date)
        .def("set_max_results", &GoogleNews::set_max_results)
        .def("set_excluded_websites", &GoogleNews::set_excluded_websites);
    
    py::class_<GoogleSearch>(m, "GoogleSearch")
        .def(py::init<>())
        .def("_get_num_results", &GoogleSearch::_get_num_results)
        .def("_get_start_index", &GoogleSearch::_get_start_index)
        .def("_get_filter", &GoogleSearch::_get_filter)
        .def("_get_c2coff", &GoogleSearch::_get_c2coff)
        .def("_get_date_restrict", &GoogleSearch::_get_date_restrict)
        .def("_get_query", &GoogleSearch::_get_query)
        .def("_get_search_url", &GoogleSearch::_get_search_url)
        .def("_get_extra_query", &GoogleSearch::_get_extra_query)
        .def("_get_exact_terms", &GoogleSearch::_get_exact_terms)
        .def("_get_exclude_terms", &GoogleSearch::_get_exclude_terms)
        .def("_get_site_search", &GoogleSearch::_get_site_search)
        .def("_get_site_search_filter", &GoogleSearch::_get_site_search_filter)
        .def("_get_link_site", &GoogleSearch::_get_link_site)
        .def("_get_or_terms", &GoogleSearch::_get_or_terms)
        .def("_get_date_restrict_type", &GoogleSearch::_get_date_restrict_type)
        .def("_get_low_range", &GoogleSearch::_get_low_range)
        .def("_get_high_range", &GoogleSearch::_get_high_range)
        .def("_get_search_type", &GoogleSearch::_get_search_type)
        .def("_get_filetype", &GoogleSearch::_get_filetype)
        .def("_get_rights", &GoogleSearch::_get_rights)
        .def("_get_img_size", &GoogleSearch::_get_img_size)
        .def("_get_img_type", &GoogleSearch::_get_img_type)
        .def("_get_img_color_type", &GoogleSearch::_get_img_color_type)
        .def("_get_img_dominant_color", &GoogleSearch::_get_img_dominant_color)
        .def("_get_language", &GoogleSearch::_get_language)
        .def("_get_interface_language", &GoogleSearch::_get_interface_language)
        .def("_get_user_country", &GoogleSearch::_get_user_country)
        .def("_get_result_country", &GoogleSearch::_get_result_country)
        .def("_get_safe", &GoogleSearch::_get_safe)
        .def("_get_sort", &GoogleSearch::_get_sort)
        .def("_get_json_file", &GoogleSearch::_get_json_file)
        .def("_get_env_file", &GoogleSearch::_get_env_file)
        .def("_set_num_results", &GoogleSearch::_set_num_results)
        .def("_set_start_index", &GoogleSearch::_set_start_index)
        .def("_set_filter", &GoogleSearch::_set_filter)
        .def("_set_c2coff", &GoogleSearch::_set_c2coff)
        .def("_set_date_restrict", &GoogleSearch::_set_date_restrict)
        .def("_set_extra_query", &GoogleSearch::_set_extra_query)
        .def("_set_exact_terms", &GoogleSearch::_set_exact_terms)
        .def("_set_exclude_terms", &GoogleSearch::_set_exclude_terms)
        .def("_set_site_search", &GoogleSearch::_set_site_search)
        .def("_set_site_search_filter", &GoogleSearch::_set_site_search_filter)
        .def("_set_link_site", &GoogleSearch::_set_link_site)
        .def("_set_or_terms", &GoogleSearch::_set_or_terms)
        .def("_set_date_restrict_type", &GoogleSearch::_set_date_restrict_type)
        .def("_set_low_range", &GoogleSearch::_set_low_range)
        .def("_set_high_range", &GoogleSearch::_set_high_range)
        .def("_set_search_type", &GoogleSearch::_set_search_type)
        .def("_set_filetype", &GoogleSearch::_set_filetype)
        .def("_set_rights", &GoogleSearch::_set_rights)
        .def("_set_img_size", &GoogleSearch::_set_img_size)
        .def("_set_img_type", &GoogleSearch::_set_img_type)
        .def("_set_img_color_type", &GoogleSearch::_set_img_color_type)
        .def("_set_img_dominant_color", &GoogleSearch::_set_img_dominant_color)
        .def("_set_language", &GoogleSearch::_set_language)
        .def("_set_interface_language", &GoogleSearch::_set_interface_language)
        .def("_set_user_country", &GoogleSearch::_set_user_country)
        .def("_set_result_country", &GoogleSearch::_set_result_country)
        .def("_set_safe", &GoogleSearch::_set_safe)
        .def("_set_sort", &GoogleSearch::_set_sort)
        .def("_set_response_file", &GoogleSearch::_set_response_file)
        .def("_set_env_file", &GoogleSearch::_set_env_file)
        .def("_search_google", &GoogleSearch::_search_google)
        .def("_get_result", &GoogleSearch::_get_result);
}
