.TH "program_files Directory Reference" 3 "AI Ecosystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
program_files Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBapplication_configure\&.cpp\fP"
.br
.ti -1c
.RI "file \fBfile_configure\&.cpp\fP"
.br
.ti -1c
.RI "file \fBfolder_configure\&.cpp\fP"
.br
.ti -1c
.RI "file \fBnews_configure\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsearch_configure\&.cpp\fP"
.br
.in -1c
