.TH "application_configure.cpp" 3 "AI Ecosystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
application_configure.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <X11/Xatom\&.h>\fP
.br
\fC#include <X11/Xlib\&.h>\fP
.br
\fC#include <sys/select\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/wait\&.h>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <pwd\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include '\&.\&./header_files/file_configure\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBApplication\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AI Ecosystem from the source code\&.
