.TH "File" 3 "AI Ecosystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
File \- Class for file manipulation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <file_configure\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFile\fP ()"
.br
.RI "Class Constructor\&. "
.ti -1c
.RI "\fB~File\fP ()"
.br
.RI "Class Destructor\&. "
.ti -1c
.RI "std::map< std::string, std::string > \fB_class_info\fP ()"
.br
.ti -1c
.RI "void \fB_create_file\fP (const std::string filename, const std::string file_path)"
.br
.RI "Function to create a file\&. "
.ti -1c
.RI "void \fB_write_file\fP (const std::string filename, const std::string content, const std::string file_path)"
.br
.RI "Function to write to a file\&. "
.ti -1c
.RI "std::string \fB_read_file\fP (const std::string filename, const std::string file_path)"
.br
.RI "Function to read a file\&. "
.ti -1c
.RI "void \fB_delete_file\fP (const std::string filename, const std::string file_path)"
.br
.RI "Function to delete a file\&. "
.ti -1c
.RI "void \fB_rename_file\fP (const std::string filename, const std::string new_filename, const std::string file_path)"
.br
.RI "Function to rename a file\&. "
.ti -1c
.RI "void \fB_move_file\fP (const std::string filename, const std::string new_path, const std::string file_path)"
.br
.RI "Function to move a file\&. "
.ti -1c
.RI "void \fB_copy_file\fP (const std::string filename, const std::string new_path, const std::string file_path)"
.br
.RI "Function to copy a file\&. "
.ti -1c
.RI "bool \fB_check_file\fP (const std::string filename, const std::string file_path)"
.br
.RI "Function to check if it is a file\&. "
.ti -1c
.RI "void \fB_hide_file\fP (const std::string filename, const std::string file_path)"
.br
.RI "Function to hide a file\&. "
.ti -1c
.RI "void \fB_unhide_file\fP (const std::string filename, const std::string file_path)"
.br
.RI "Function to unhide a file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class for file manipulation\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "File::File ()"

.PP
Class Constructor\&. 
.SS "File::~File ()"

.PP
Class Destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool File::_check_file (const std::string filename, const std::string file_path = \fC''\fP)"

.PP
Function to check if it is a file\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP Name of the file 
.br
\fIfile_path\fP Path of the file 
.RE
.PP
\fBReturns\fP
.RS 4
True if it is a file, false otherwise 
.RE
.PP

.SS "std::map< std::string, std::string > File::_class_info ()"

.SS "void File::_copy_file (const std::string filename, const std::string new_path, const std::string file_path = \fC''\fP)"

.PP
Function to copy a file\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP Name of the file 
.br
\fInew_path\fP New path of the file 
.br
\fIfile_path\fP Path of the file 
.RE
.PP

.SS "void File::_create_file (const std::string filename, const std::string file_path = \fC''\fP)"

.PP
Function to create a file\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP Name of the file 
.br
\fIfile_path\fP Path of the file 
.RE
.PP

.SS "void File::_delete_file (const std::string filename, const std::string file_path = \fC''\fP)"

.PP
Function to delete a file\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP Name of the file 
.br
\fIfile_path\fP Path of the file 
.RE
.PP

.SS "void File::_hide_file (const std::string filename, const std::string file_path = \fC''\fP)"

.PP
Function to hide a file\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP Name of the file 
.br
\fIfile_path\fP Path of the file 
.RE
.PP

.SS "void File::_move_file (const std::string filename, const std::string new_path, const std::string file_path = \fC''\fP)"

.PP
Function to move a file\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP Name of the file 
.br
\fInew_path\fP New path of the file 
.br
\fIfile_path\fP Path of the file 
.RE
.PP

.SS "std::string File::_read_file (const std::string filename, const std::string file_path = \fC''\fP)"

.PP
Function to read a file\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP Name of the file 
.br
\fIfile_path\fP Path of the file 
.RE
.PP
\fBReturns\fP
.RS 4
Content of the file 
.RE
.PP

.SS "void File::_rename_file (const std::string filename, const std::string new_filename, const std::string file_path = \fC''\fP)"

.PP
Function to rename a file\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP Name of the file 
.br
\fInew_filename\fP New name of the file 
.br
\fIfile_path\fP Path of the file 
.RE
.PP

.SS "void File::_unhide_file (const std::string filename, const std::string file_path = \fC''\fP)"

.PP
Function to unhide a file\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP Name of the file 
.br
\fIfile_path\fP Path of the file 
.RE
.PP

.SS "void File::_write_file (const std::string filename, const std::string content, const std::string file_path = \fC''\fP)"

.PP
Function to write to a file\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP Name of the file 
.br
\fIcontent\fP Content of the file 
.br
\fIfile_path\fP Path of the file 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AI Ecosystem from the source code\&.
