.TH "file_configure.cpp" 3 "AI Ecosystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file_configure.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./header_files/file_configure\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::map< std::string, std::string > \fB_class_info\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::map< std::string, std::string > _class_info ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for AI Ecosystem from the source code\&.
