.TH "file_configure.h" 3 "AI Ecosystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file_configure.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <map>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBFile\fP"
.br
.RI "Class for file manipulation\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AI Ecosystem from the source code\&.
