.TH "folder_configure.h" 3 "AI Ecosystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
folder_configure.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <filesystem>\fP
.br
\fC#include <fstream>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBFolder\fP"
.br
.RI "Class for folder manipulation\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AI Ecosystem from the source code\&.
