.TH "gemini_configure.py" 3 "AI Ecosystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gemini_configure.py
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBgemini_configure\&.GeminiModel\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgemini_configure\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AI Ecosystem from the source code\&.
