.TH "gemini_configure.GeminiModel" 3 "AI Ecosystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gemini_configure.GeminiModel
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self)"
.br
.ti -1c
.RI "str \fBquery_model\fP (self, str query, False verbose)"
.br
.ti -1c
.RI "list \fBget_available_models\fP (self)"
.br
.ti -1c
.RI "None \fBmodify_safety_settings\fP (self, HarmCategory\&.name safety, HarmBlockThreshold\&.name setting=HarmBlockThreshold\&.BLOCK_LOW_AND_ABOVE)"
.br
.ti -1c
.RI "object \fBget_current_configuration\fP (self)"
.br
.ti -1c
.RI "None \fBset_configuration\fP (self, int|None candidate_count=None, Iterable[str]|None stop_sequences=None, int|None max_output_tokens=None, float|None temperature=None, float|None top_p=None, int|None top_k=None, str|None response_mime_type=None, Mapping[str, Any]|None response_schema=None)"
.br
.ti -1c
.RI "genai\&.GenerativeModel \fBget_model\fP (self)"
.br
.ti -1c
.RI "None \fBset_model\fP (self, str model_name, str|None system_message=None, Mapping[HarmCategory:HarmBlockThreshold]|None safety_settings=None)"
.br
.ti -1c
.RI "list \fBload_history\fP (self, str filename='json_files/gemini_history\&.json')"
.br
.ti -1c
.RI "None \fBclear_history\fP (self, str filename='json_files/gemini_history\&.json')"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "str \fB_get_previous_messages\fP (self)"
.br
.ti -1c
.RI "None \fB_save_history\fP (self, str filename='json_files/gemini_history\&.json')"
.br
.ti -1c
.RI "None \fB_configure_model\fP (self)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_model_name\fP"
.br
.ti -1c
.RI "\fB_context\fP"
.br
.ti -1c
.RI "\fB_history\fP"
.br
.ti -1c
.RI "\fB_safety_settings\fP"
.br
.ti -1c
.RI "\fB_configuration\fP"
.br
.ti -1c
.RI "\fB_model\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None gemini_configure\&.GeminiModel\&.__init__ ( self)"

.PP
.nf
    Args:
        None
    
    Returns:
        None
    
    Summary:
        Initializes the GeminiModel class\&.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " None gemini_configure\&.GeminiModel\&._configure_model ( self)\fC [protected]\fP"

.PP
.nf
    Args:
        None
    
    Returns:
        None
    
    Summary:
        Configures the model with the given configuration

.fi
.PP
 
.SS " str gemini_configure\&.GeminiModel\&._get_previous_messages ( self)\fC [protected]\fP"

.PP
.nf
    Args:
        None
    
    Returns:
        String of the previous messages by USER and ASSISTANT
    
    Summary:
        Returns the previous messages by USER and ASSISTANT

.fi
.PP
 
.SS " None gemini_configure\&.GeminiModel\&._save_history ( self, str filename = \fC'json_files/gemini_history\&.json'\fP)\fC [protected]\fP"

.PP
.nf
    Args:
        filename: Name of the file to save the history to
    
    Returns:
        None
    
    Summary:
        Saves the history to the given file

.fi
.PP
 
.SS " None gemini_configure\&.GeminiModel\&.clear_history ( self, str filename = \fC'json_files/gemini_history\&.json'\fP)"

.PP
.nf
    Args:
        filename: Name of the file to clear the history from
    
    Returns:
        None
    
    Summary:
        Clears the history from the given file

.fi
.PP
 
.SS " list gemini_configure\&.GeminiModel\&.get_available_models ( self)"

.PP
.nf
    Args:
        None
    
    Returns
        List of model names
    
    Summary:
        Returns a list of model names available with the current api

.fi
.PP
 
.SS " object gemini_configure\&.GeminiModel\&.get_current_configuration ( self)"

.PP
.nf
    Args:
        None
    
    Returns:
        None
    
    Summary:
        Returns the current configuration of the model\&.

.fi
.PP
 
.SS " genai\&.GenerativeModel gemini_configure\&.GeminiModel\&.get_model ( self)"

.PP
.nf
    Args:
        None
    
    Returns:
        None
    
    Summary:
        Returns the current model being used\&.

.fi
.PP
 
.SS " list gemini_configure\&.GeminiModel\&.load_history ( self, str filename = \fC'json_files/gemini_history\&.json'\fP)"

.PP
.nf
    Args:
        filename: Name of the file to load the history from
    
    Returns:
        None
    
    Summary:
        Loads the history from the given file

.fi
.PP
 
.SS " None gemini_configure\&.GeminiModel\&.modify_safety_settings ( self, HarmCategory\&.name safety, HarmBlockThreshold\&.name  setting = \fCHarmBlockThreshold\&.BLOCK_LOW_AND_ABOVE\fP)"

.PP
.nf
    Args:
        safety: Safety Category to change
        setting: Content level to block for the category
    
    Returns:
        None
    
    Summary:
        Changes the safety settings for the content generated by the model

.fi
.PP
 
.SS " str gemini_configure\&.GeminiModel\&.query_model ( self, str query, False verbose)"

.PP
.nf
    Args:
        query: The prompt you wish to ask gemini
        verbose: Whether to print the responce in verbose mode
    
    Returns:
        String of responce given by gemini
    
    Summary:
        Asks the gemini model the given prompt with the previous history and returns the responce\&.

.fi
.PP
 
.SS " None gemini_configure\&.GeminiModel\&.set_configuration ( self, int | None  candidate_count = \fCNone\fP, Iterable[str] | None  stop_sequences = \fCNone\fP, int | None  max_output_tokens = \fCNone\fP, float | None  temperature = \fCNone\fP, float | None  top_p = \fCNone\fP, int | None  top_k = \fCNone\fP, str | None  response_mime_type = \fCNone\fP, Mapping[str, Any] | None  response_schema = \fCNone\fP)"

.PP
.nf
    Args:
        candidate_count: The number of candidate
        stop_sequences: List of string to stop the generation at
        max_output_tokens: How many token's output must gemini model give
        temperature: Controls the randomness of the output\&.
        top_p: The maximum cumulative probability of tokens to consider when sampling\&.
        top_k: The maximum number of tokens to consider when sampling\&.
        response_mime_type: Output response mimetype of the generated candidate text\&.
        response_schema: Specifies the format of the JSON requested if response_mime_type is application/json\&.
    
    Returns:
        None
    
    Summary:
        Sets the configuration of the model\&.

.fi
.PP
 
.SS " None gemini_configure\&.GeminiModel\&.set_model ( self, str model_name, str | None  system_message = \fCNone\fP, Mapping[HarmCategory: HarmBlockThreshold] | None  safety_settings = \fCNone\fP)"

.PP
.nf
    Args:
        model_name: Name of the model you want to use
        system_message: System message for the model

    Returns:
        None
    
    Summary:
        Sets the new model name and system message if given

.fi
.PP
 
.SH "Field Documentation"
.PP 
.SS "gemini_configure\&.GeminiModel\&._configuration\fC [protected]\fP"

.SS "gemini_configure\&.GeminiModel\&._context\fC [protected]\fP"

.SS "gemini_configure\&.GeminiModel\&._history\fC [protected]\fP"

.SS "gemini_configure\&.GeminiModel\&._model\fC [protected]\fP"

.SS "gemini_configure\&.GeminiModel\&._model_name\fC [protected]\fP"

.SS "gemini_configure\&.GeminiModel\&._safety_settings\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AI Ecosystem from the source code\&.
