.TH "GoogleNews" 3 "AI Ecosystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GoogleNews \- Class to Search News on Google News\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <news_configure\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGoogleNews\fP (const std::string language, const std::string country, const std::string period, const std::string start_date, const std::string end_date, const int max_results, const std::vector< std::string > exclude_websites)"
.br
.RI "Initialize google news constructor with default parameters\&. "
.ti -1c
.RI "\fB~GoogleNews\fP ()"
.br
.RI "Class Destructor\&. "
.ti -1c
.RI "std::string \fB_get_language\fP ()"
.br
.RI "Function to get the language\&. "
.ti -1c
.RI "std::string \fB_get_country\fP ()"
.br
.RI "Function to get the country\&. "
.ti -1c
.RI "std::string \fB_get_period\fP ()"
.br
.RI "Function to get the period\&. "
.ti -1c
.RI "std::string \fB_get_start_date\fP ()"
.br
.RI "Function to get the start date\&. "
.ti -1c
.RI "std::string \fB_get_end_date\fP ()"
.br
.RI "Function to get the end date\&. "
.ti -1c
.RI "int \fB_get_max_results\fP ()"
.br
.RI "Function to get the max results\&. "
.ti -1c
.RI "std::vector< std::string > \fB_get_exclude_websites\fP ()"
.br
.RI "Function to get the excluded websites\&. "
.ti -1c
.RI "void \fB_get_news\fP (const std::string keyword, const std::string filename)"
.br
.RI "Function to get the news\&. "
.ti -1c
.RI "void \fB_get_latest_topics\fP (const std::string filename)"
.br
.RI "Function to get the news on latest topics\&. "
.ti -1c
.RI "void \fB_get_news_by_topic\fP (const std::string topic, const std::string filename)"
.br
.RI "Function to get the news on the given topic\&. "
.ti -1c
.RI "void \fB_get_news_by_country\fP (const std::string country, const std::string filename)"
.br
.RI "Function to get the news on the given country\&. "
.ti -1c
.RI "void \fB_get_news_by_site\fP (const std::string site, const std::string filename)"
.br
.RI "Function to get the news from the given site\&. "
.ti -1c
.RI "void \fB_set_language\fP (const std::string language)"
.br
.RI "Function to set the language\&. "
.ti -1c
.RI "void \fB_set_country\fP (const std::string country)"
.br
.RI "Function to set the country\&. "
.ti -1c
.RI "void \fB_set_period\fP (const std::string period)"
.br
.RI "Function to set the time period\&. "
.ti -1c
.RI "bool \fB_set_start_date\fP (const std::string start_date)"
.br
.RI "Function to set the start date\&. "
.ti -1c
.RI "bool \fB_set_end_date\fP (const std::string end_date)"
.br
.RI "Function to set the end date\&. "
.ti -1c
.RI "void \fB_set_max_results\fP (const int max_results)"
.br
.RI "Function to set the max results\&. "
.ti -1c
.RI "void \fB_set_excluded_websites\fP (std::vector< std::string > excluded_websites)"
.br
.RI "Function to set the excluded websites\&. "
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fB_max_results\fP"
.br
.ti -1c
.RI "std::string \fB_language\fP"
.br
.ti -1c
.RI "std::string \fB_country\fP"
.br
.ti -1c
.RI "std::string \fB_period\fP"
.br
.ti -1c
.RI "std::string \fB_start_date\fP"
.br
.ti -1c
.RI "std::string \fB_end_date\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fB_exclude_websites\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class to Search News on Google News\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GoogleNews::GoogleNews (const std::string language = \fC'en'\fP, const std::string country = \fC'US'\fP, const std::string period = \fC'anytime'\fP, const std::string start_date = \fC''\fP, const std::string end_date = \fC''\fP, const int max_results = \fC10\fP, const std::vector< std::string > exclude_websites = \fC{}\fP)"

.PP
Initialize google news constructor with default parameters\&. 
.PP
\fBParameters\fP
.RS 4
\fIlanguage\fP Languge you want to get the news in 
.br
\fIcountry\fP Country you want to get the news from 
.br
\fIperiod\fP Time period to get news from 
.br
\fIstart_date\fP Starting date for when to get news from 
.br
\fIend_date\fP Ending date for when to get the news till\&. End date should be atleast 1 day after start date 
.br
\fImax_results\fP Max number of results to be returned for the news 
.br
\fIexclude_websites\fP Websites to exclude when searching for the news 
.RE
.PP

.SS "GoogleNews::~GoogleNews ()"

.PP
Class Destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "std::string GoogleNews::_get_country ()"

.PP
Function to get the country\&. 
.PP
\fBReturns\fP
.RS 4
String of the country 
.RE
.PP

.SS "std::string GoogleNews::_get_end_date ()"

.PP
Function to get the end date\&. 
.PP
\fBReturns\fP
.RS 4
String of the date 
.RE
.PP

.SS "std::vector< std::string > GoogleNews::_get_exclude_websites ()"

.PP
Function to get the excluded websites\&. 
.PP
\fBReturns\fP
.RS 4
Vector of excluded websites 
.RE
.PP

.SS "std::string GoogleNews::_get_language ()"

.PP
Function to get the language\&. 
.PP
\fBReturns\fP
.RS 4
String of the language 
.RE
.PP

.SS "void GoogleNews::_get_latest_topics (const std::string filename = \fC'text_files/news_articles\&.txt'\fP)"

.PP
Function to get the news on latest topics\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP \fBFile\fP to save articles in 
.RE
.PP

.SS "int GoogleNews::_get_max_results ()"

.PP
Function to get the max results\&. 
.PP
\fBReturns\fP
.RS 4
Number of max results 
.RE
.PP

.SS "void GoogleNews::_get_news (const std::string keyword, const std::string filename = \fC'text_files/news_articles\&.txt'\fP)"

.PP
Function to get the news\&. 
.PP
\fBParameters\fP
.RS 4
\fIkeyword\fP Keyword used to search news 
.br
\fIfilename\fP \fBFile\fP to save articles in 
.RE
.PP

.SS "void GoogleNews::_get_news_by_country (const std::string country, const std::string filename = \fC'text_files/news_articles\&.txt'\fP)"

.PP
Function to get the news on the given country\&. 
.PP
\fBParameters\fP
.RS 4
\fIcountry\fP Search the news on this country 
.br
\fIfilename\fP \fBFile\fP to save articles in 
.RE
.PP

.SS "void GoogleNews::_get_news_by_site (const std::string site, const std::string filename = \fC'text_files/news_articles\&.txt'\fP)"

.PP
Function to get the news from the given site\&. 
.PP
\fBParameters\fP
.RS 4
\fIsite\fP Search the news from this site 
.br
\fIfilename\fP \fBFile\fP to save articles in 
.RE
.PP

.SS "void GoogleNews::_get_news_by_topic (const std::string topic, const std::string filename = \fC'text_files/news_articles\&.txt'\fP)"

.PP
Function to get the news on the given topic\&. 
.PP
\fBParameters\fP
.RS 4
\fItopic\fP Search the news on this topic 
.br
\fIfilename\fP \fBFile\fP to save articles in 
.RE
.PP

.SS "std::string GoogleNews::_get_period ()"

.PP
Function to get the period\&. 
.PP
\fBReturns\fP
.RS 4
String of the period 
.RE
.PP

.SS "std::string GoogleNews::_get_start_date ()"

.PP
Function to get the start date\&. 
.PP
\fBReturns\fP
.RS 4
String of the date 
.RE
.PP

.SS "void GoogleNews::_set_country (const std::string country)"

.PP
Function to set the country\&. 
.PP
\fBParameters\fP
.RS 4
\fIcountry\fP Country you want to get the news from 
.RE
.PP

.SS "bool GoogleNews::_set_end_date (const std::string end_date)"

.PP
Function to set the end date\&. 
.PP
\fBParameters\fP
.RS 4
\fIend_date\fP Ending date till when news is presented 
.RE
.PP
\fBReturns\fP
.RS 4
True if start date and end date are different 
.RE
.PP

.SS "void GoogleNews::_set_excluded_websites (std::vector< std::string > excluded_websites)"

.PP
Function to set the excluded websites\&. 
.PP
\fBParameters\fP
.RS 4
\fIexcluded_websites\fP Websites to exclude from the results 
.RE
.PP

.SS "void GoogleNews::_set_language (const std::string language)"

.PP
Function to set the language\&. 
.PP
\fBParameters\fP
.RS 4
\fIlanguage\fP Languge you want to get the news in 
.RE
.PP

.SS "void GoogleNews::_set_max_results (const int max_results)"

.PP
Function to set the max results\&. 
.PP
\fBParameters\fP
.RS 4
\fImax_results\fP Max number of results for the news 
.RE
.PP

.SS "void GoogleNews::_set_period (const std::string period)"

.PP
Function to set the time period\&. 
.PP
\fBParameters\fP
.RS 4
\fIperiod\fP Time period to get news from 
.RE
.PP

.SS "bool GoogleNews::_set_start_date (const std::string start_date)"

.PP
Function to set the start date\&. 
.PP
\fBParameters\fP
.RS 4
\fIstart_date\fP Starting date for when to get news from 
.RE
.PP
\fBReturns\fP
.RS 4
True if start date and end date are different 
.RE
.PP

.SH "Field Documentation"
.PP 
.SS "std::string GoogleNews::_country"

.SS "std::string GoogleNews::_end_date"

.SS "std::vector<std::string> GoogleNews::_exclude_websites"

.SS "std::string GoogleNews::_language"

.SS "int GoogleNews::_max_results"

.SS "std::string GoogleNews::_period"

.SS "std::string GoogleNews::_start_date"


.SH "Author"
.PP 
Generated automatically by Doxygen for AI Ecosystem from the source code\&.
