.TH "news_configure.h" 3 "AI Ecosystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
news_configure.h
.SH SYNOPSIS
.br
.PP
\fC#include <ctime>\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <unordered_map>\fP
.br
\fC#include <unordered_set>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <curl/curl\&.h>\fP
.br
\fC#include 'tinyxml2\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBGoogleNews\fP"
.br
.RI "Class to Search News on Google News\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AI Ecosystem from the source code\&.
