.TH "search_configure.h" 3 "AI Ecosystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
search_configure.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <curl/curl\&.h>\fP
.br
\fC#include <unordered_map>\fP
.br
\fC#include <nlohmann/json\&.hpp>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBGoogleSearch\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AI Ecosystem from the source code\&.
