.TH "setup.py" 3 "AI Ecosystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
setup.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsetup\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBsetup\&.ext_modules\fP"
.br
.ti -1c
.RI "\fBsetup\&.name\fP"
.br
.ti -1c
.RI "\fBsetup\&.version\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AI Ecosystem from the source code\&.
